### ISSUE TITLE
Remove dependency on MenuAPI or be able to toggle between menuAPI and esx_menu_ui

### ISSUE THREAD

**Issue by LenaMatoi** [Xogy/rcore_arcade#4]
In the video it appears as you use menu ui but then you indicate that it needs a dependency called MenuAPI, it gives an option to not require that dependency since it is only a simple menu theme that consumes resources.

**Comment by Xogy** [comment]
The reason I have switched to my MenuAPI is that people wanted it on other frameworks than ESX. And from personal experiences, I know that people do not even read: "readme.MD" or description in config.lua.

So there would be tons of other "issues" because people don't know how to even read. 

Both of these resources take 0.02ms combined together when AFK... Feel free to add support to ESX Menu UI but there won't be any support for this because like I said above it would cause just more trouble. 

Thanks and have a great day.
